// Copyright 2014 The Azul3D Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
//
// Code generated by this program is also under
// the above license.

// glwrap is a tool for generating Go OpenGL wrappers.
package main

import (
	"io"
	"text/template"
)

const enumsTemplate = `// Copyright 2014 The Azul3D Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
//
// This source file was automatically generated using glwrap.{{range $tag := .BuildTags}}
// +build {{$tag}}{{end}}

package {{.API}}

const(
{{range $element := .Constants}}	{{.Name}} {{.Type}} = {{.Value}}
{{end}}
)
`

func writeEnums(out io.Writer, tmplData *TmplData) error {
	tmpl := template.Must(template.New("enumsTemplate").Parse(enumsTemplate))
	err = tmpl.Execute(out, map[string]interface{}{
		"BuildTags": tmplData.BuildTags,
		"Constants": tmplData.Constants,
		"Title":     tmplData.Title,
		"API":       tmplData.API,
	})
	if err != nil {
		return err
	}
	return nil
}
